### ISSUE TITLE
zip files are corrupted 

### ISSUE THREAD

**Issue by pfragoso** [IBM/core-dump-handler#6] opened 2021-08-12 11:36 UTC
Hello,

I have deployed core-dump-handler in a k8s cluster and it's currently sending coredump to s3 as intended.

The only issue is that all the files that get sent to s3 are corrupted.

```
core-dump-handler-gclrk coredump-container [2021-08-12T09:10:42Z INFO  core_dump_agent] Dir Content ["/var/mnt/core-dump-handler/core/4739e2b1-565f-4336-99d9-f25f5d4c8516-dump-1628759416-busybox-sh-6-11.zip"]
core-dump-handler-gclrk coredump-container [2021-08-12T09:10:42Z INFO  core_dump_agent] Uploading: /var/mnt/core-dump-handler/core/4739e2b1-565f-4336-99d9-f25f5d4c8516-dump-1628759416-busybox-sh-6-11.zip
core-dump-handler-gclrk coredump-container [2021-08-12T09:10:42Z INFO  core_dump_agent] zip size is 368
core-dump-handler-gclrk coredump-container [2021-08-12T09:10:42Z INFO  core_dump_agent] S3 Returned: 200
```

```
➜ unzip 4739e2b1-565f-4336-99d9-f25f5d4c8516-dump-1628759416-busybox-sh-6-11.zip
Archive:  4739e2b1-565f-4336-99d9-f25f5d4c8516-dump-1628759416-busybox-sh-6-11.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 4739e2b1-565f-4336-99d9-f25f5d4c8516-dump-1628759416-busybox-sh-6-11.zip or
        4739e2b1-565f-4336-99d9-f25f5d4c8516-dump-1628759416-busybox-sh-6-11.zip.zip, and cannot find 4739e2b1-565f-4336-99d9-f25f5d4c8516-dump-1628759416-busybox-sh-6-11.zip.ZIP, period.
```

This happens to all files. Tried downloading via Browser and via aws CLI same result.

**Comment by andytson-inviqa** [comment] 2021-08-17 10:50
This appears to happen when the k8s host node doesn't have crictl installed. Perhaps that should be a soft warning and avoid including that metadata in the zip if it isn't installed?

**Comment by andytson** [comment] 2021-08-17 10:52
This appears to be caused when crictl isn't available on the K8s host node, which causes the command to finish before it's flushed and ended the zip file. Perhaps this could be a soft warning and continue without the metadata if the command doesn't exist?

**Comment by No9** [comment] 2021-08-19 08:21
Thanks for reporting this. 
The behaviour @andytson outlines with the soft warning is the intent but it looks like there is a problem with the logic.
Can I ask which container runtime your cluster is running?

**Comment by pfragoso** [comment] 2021-08-23 10:10
Hello,

This is running on EKS with the docker container runtime.

**Comment by No9** [comment] 2021-08-25 10:26
Perfect thanks for the reproduction steps. 
I have been looking for a reason to do the validation for EKS for the matrix in the readme. I'll take a look

**Comment by andytson** [comment] 2021-09-01 09:39
@No9 I can confirm on @pfragoso's behalf that the 2.0.11 release fixes the issue. New zips are valid and contain just the *.core and *-dump-info.json files

**Comment by No9** [comment] 2021-09-02 12:04
Thanks @andytson and @pfragoso for all the feedback 
I'll close this and if there is anything additional please feel free to open up another issue.

**Closed by No9** 2021-09-02 12:04 UTC
